from movie_recommendation.similarity import update_similarity_matrix
from movie_recommendation.weighted_rating import update_weighted_rating

update_similarity_matrix()
update_weighted_rating()

from movie_recommendation.recommendation import mr